### ISSUE TITLE
Impossible installation under Win 7

### ISSUE THREAD

**Issue by mefjuu** [couto/grunt-groundskeeper#4]
Error lines from .log:

```
1090 verbose false,D:\htdocs\demo\node_modules,D:\htdocs\demo\node_modules\grunt-groundskeeper\node_modules unbuild groundskeeper@0.1.3
1091 verbose D:\htdocs\demo\node_modules\grunt-groundskeeper\node_modules\.bin,[object Object] binRoot
1092 info postuninstall groundskeeper@0.1.3
1093 error error rolling back Error: ENOTEMPTY, rmdir 'D:\htdocs\demo\node_modules\grunt-groundskeeper\node_modules\groundskeeper\node_modules\esprima\test'
1093 error error rolling back  groundskeeper@0.1.3 { [Error: ENOTEMPTY, rmdir 'D:\htdocs\demo\node_modules\grunt-groundskeeper\node_modules\groundskeeper\node_modules\esprima\test']
1093 error error rolling back   errno: 53,
1093 error error rolling back   code: 'ENOTEMPTY',
1093 error error rolling back   path: 'D:\\htdocs\\demo\\node_modules\\grunt-groundskeeper\\node_modules\\groundskeeper\\node_modules\\esprima\\test' }
1094 verbose about to build D:\htdocs\demo\node_modules\grunt-groundskeeper
1095 info D:\htdocs\demo\node_modules\grunt-groundskeeper unbuild
1096 verbose from cache D:\htdocs\demo\node_modules\grunt-groundskeeper\package.json
1097 info preuninstall grunt-groundskeeper@0.1.4
1098 info uninstall grunt-groundskeeper@0.1.4
1099 verbose true,D:\htdocs\demo\node_modules,D:\htdocs\demo\node_modules unbuild grunt-groundskeeper@0.1.4
1100 verbose D:\htdocs\demo\node_modules\.bin,[object Object] binRoot
1101 info postuninstall grunt-groundskeeper@0.1.4
1102 error error rolling back Error: EPERM, rmdir 'D:\htdocs\demo\node_modules\grunt-groundskeeper\node_modules\groundskeeper\node_modules\esprima\test\test.js'
1102 error error rolling back  grunt-groundskeeper@0.1.4 { [Error: EPERM, rmdir 'D:\htdocs\demo\node_modules\grunt-groundskeeper\node_modules\groundskeeper\node_modules\esprima\test\test.js']
1102 error error rolling back   errno: 50,
1102 error error rolling back   code: 'EPERM',
1102 error error rolling back   path: 'D:\\htdocs\\demo\\node_modules\\grunt-groundskeeper\\node_modules\\groundskeeper\\node_modules\\esprima\\test\\test.js' }
1103 error Error: No compatible version found: esprima@'substack/esprima#is-keyword'
1103 error Valid install targets:
1103 error ["0.7.0","0.8.0","0.8.1","0.8.2","0.9.0","0.9.1","0.9.2","0.9.3","0.9.4","0.9.5","0.9.6","0.9.7","0.9.8","0.9.9","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4"]
1103 error     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\lib\cache.js:719:10)
1103 error     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:641:10
1103 error     at RegClient.get_ (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:101:14)
1103 error     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:37:12)
1103 error     at fs.js:266:14
1103 error     at Object.oncomplete (fs.js:107:15)
1104 error If you need help, you may report this log at:
1104 error     <http://github.com/isaacs/npm/issues>
1104 error or email it to:
1104 error     <npm-@googlegroups.com>
1105 error System Windows_NT 6.1.7601
1106 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-groundskeeper"
1107 error cwd D:\htdocs\demo
1108 error node -v v0.10.12
1109 error npm -v 1.2.32
1110 verbose exit [ 1, true ]
```

**Comment by couto** [comment]
I don't have access to a  windows machine at the moment, however I'll try to replicate your bug and fix it as soon as possible.

**Comment by couto** [comment]
Ok. I've just spent some minutes on this problem, and it seems that something went wrong with `groundskeeper`'s dependencies.

I've just updated them, and it now installs fine on my machine, however, Windows is way out of my comfort zone, would you mind give it a try, just to be sure? Thanks.

**Comment by mefjuu** [comment]
Ok, now the installation process is going well.
Thanks a lot for quick response!
